version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install pytest
  build:
    commands:
      - echo Running tests sequentially...
      - pytest tests/ --maxfail=5 --disable-warnings --tb=short

artifacts:
  files:
    - '**/*'
  discard-paths: yes
