version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install pytest pytest-xdist
  build:
    commands:
      - echo Running tests in parallel...
      - pytest tests/ --maxfail=5 --disable-warnings -n auto --tb=short

artifacts:
  files:
    - '**/*'
  discard-paths: yes
